const convertFormInfoApiResult = (result) => {
	const [
		id,
		facultyName,
		departmentName,
		disciplineName,
		degreeName,
		fielfOfStudyName,
		specialtyName,
		educationalProgram,
		docApprovedByPosition,
		docApprovedByName,
		created_at,
		epCreatedByPosition,
		epCreatedByDegree,
		epCreatedByName,
		epApprovedFirstByPosition,
		epApprovedFirstByDegree,
		epApprovedFirstByName,
		epApprovedSecondByPosition,
		epApprovedSecondByDegree,
		epApprovedSecondByName,
		epApprovedThirdByPosition,
		epApprovedThirdByDegree,
		epApprovedThirdByName,
		epApprovedTotallyByPosition,
		epApprovedTotallyByDegree,
		epApprovedTotallyByName,
		creditsAmount,
		modulesAmount,
		contentModulesAmount,
		individualTasksAmount,
		prerequisites,
		goal,
		tasks,
		competences,
		programResults,
		controlMeasures,
		classroomWeeklyHours,
		individualWeeklyHours,
		language,
		fullTimeCharacteristicId,
		correspondenceCharacteristicId,
		createdById,

		eDCFullTimeCharacteristicId,
		fullTimeEducationForm,
		fullTimeYear,
		fullTimeSemester,
		fullTimeLectionsId,
		fullTimePracticalsId,
		fullTimeLabolatoriesId,
		fullTimeCourseWorkId,
		fullTimeSelfstudyId,
		fullTimeExamType,
		fullTimeMandatoring,

		eDCCorrespondenceCharacteristicId,
		correspondenceEducationForm,
		correspondenceYear,
		correspondenceSemester,
		correspondenceLectionsId,
		correspondencePracticalsId,
		correspondenceLabolatoriesId,
		correspondenceCourseWorkId,
		correspondenceSelfstudyId,
		correspondenceExamType,
		correspondenceMandatoring
	] = result;

	return {
		id,
		facultyName,
		departmentName,
		disciplineName,
		degreeName,
		fielfOfStudyName,
		specialtyName,
		educationalProgram,
		docApprovedByPosition,
		docApprovedByName,
		created_at,
		// epCreatedByPosition,
		// epCreatedByDegree,
		// epCreatedByName,
		epApprovedFirstByPosition,
		epApprovedFirstByDegree,
		epApprovedFirstByName,
		epApprovedSecondByPosition,
		epApprovedSecondByDegree,
		epApprovedSecondByName,
		epApprovedThirdByPosition,
		epApprovedThirdByDegree,
		epApprovedThirdByName,
		epApprovedTotallyByPosition,
		epApprovedTotallyByDegree,
		epApprovedTotallyByName,
		creditsAmount,
		modulesAmount,
		contentModulesAmount,
		individualTasksAmount,
		prerequisites,
		goal,
		tasks,
		competences,
		programResults,
		controlMeasures,
		classroomWeeklyHours,
		individualWeeklyHours,
		language,
		fullTimeCharacteristicId,
		correspondenceCharacteristicId,
		createdById,
		fullTimeCharacteristic: {
			id: fullTimeCharacteristicId,
			educationForm: fullTimeEducationForm,
			year: fullTimeYear,
			semester: fullTimeSemester,
			lectionsId: fullTimeLectionsId,
			practicalsId: fullTimePracticalsId,
			labolatoriesId: fullTimeLabolatoriesId,
			courseWorkId: fullTimeCourseWorkId,
			selfstudyId: fullTimeSelfstudyId,
			examType: fullTimeExamType,
			mandatoring: fullTimeMandatoring,
		},
		correspondenceCharacteristic: {
			id: correspondenceCharacteristicId,
			educationForm: correspondenceEducationForm,
			year: correspondenceYear,
			semester: correspondenceSemester,
			lectionsId: correspondenceLectionsId,
			practicalsId: correspondencePracticalsId,
			labolatoriesId: correspondenceLabolatoriesId,
			courseWorkId: correspondenceCourseWorkId,
			selfstudyId: correspondenceSelfstudyId,
			examType: correspondenceExamType,
			mandatoring: correspondenceMandatoring
		}
	};
}